name: TotalFreedomMod
main: me.totalfreedom.totalfreedommod.TotalFreedomMod
version: ${project.version}
description: Plugin for the Total Freedom server.
depend:
  - JDA
softdepend:
  - BukkitTelnet
  - CoreProtect
  - Essentials
  - LibsDisguises
  - WorldEdit
  - WorldGuard
  - WorldGuardExtraFlags
  - Votifier
authors: [Madgeek1450, Prozza]
api-version: "1.19"
libraries:
    - commons-io:commons-io:2.11.0
